build:
 version: "1.2"  
 
cards:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "Anuj Ku - QA Lead"
    email: "anujku@eazybank.com"
  onCallSupport:
    - (617) 231-2356
    - (936) 111-8721