build:
 version: "1.1" 
   
cards:
  message: "Welcome to EazyBank cards related prod APIs "
  contactDetails:
    name: "Anuj K - Product Owner"
    email: "anuj@eazybank.com"
  onCallSupport:
    - (617) 121-2356
    - (936) 212-8721