build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Bitto K - Product Owner"
    email: "bitto@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956