build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related prod APIs "
  contactDetails:
    name: "Radha K - Dev Lead"
    email: "radhak@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956